name: project1_change_appbar_color
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # dio 
  dio: ^4.0.6

  # http
  http: ^0.13.5
  
  # sign in buttons
  flutter_signin_button: ^2.0.0

  # path provider
  path_provider: ^2.0.11

  # shared pereferences
  shared_preferences: ^2.0.15 
  
  # secure storage
  flutter_secure_storage: ^7.0.1

  # sqflite
  sqflite: ^2.1.0

  # image picker
  image_picker: ^0.8.5+3

  # startflut
  # starflut: ^1.0.0

  # url launcher
  url_launcher: ^6.1.7

  # skeleton
  skeletons: ^0.0.3

  # BLoC
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0

  # env
  flutter_dotenv: ^5.0.2

  # snackbar
  top_snackbar_flutter: ^3.0.0+1

  # notifications
  flutter_local_notifications: ^13.0.0

  #rxdart
  rxdart: ^0.27.7

  # auto_route
  auto_route: ^5.0.4
  salomon_bottom_bar: ^3.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  path: ^1.8.2


  # dependcy injection
  get_it: ^7.6.0
  injectable: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # auto_route settings
  auto_route_generator: ^5.0.3
  flutter_lints: ^2.0.1

  injectable: ^2.1.2
  build_runner: ^2.3.3
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true

  assets: 
    - assets/img/nf_let-you-down.jpg
    - assets/img/_shape-on-you.jpg
    - assets/img/me.jpg
    - assets/img/butterfly.png
    - assets/img/morning.jpg
    - assets/img/night.jpg
    - assets/img/night2.jpg
    - assets/img/restaurant.jpg
    - .env


    # disaster images
    - assets/disaster/cig.jpeg
    - assets/disaster/deprem.jpeg
    - assets/disaster/yangin.jpeg
    - assets/disaster/sel.jpeg


  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
